import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Building2,Mail,Lock,KeyRound,ShieldCheck,CheckCircle2,Eye,EyeOff}from'lucide-react';import'./style.css';
const API='/api';type Page='home'|'login'|'register'|'verify'|'forgot'|'reset'|'dashboard';
async function api(path:string,body:any){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request gagal');return d}
function save(d:any){if(d.accessToken)localStorage.setItem('accessToken',d.accessToken);if(d.refreshToken)localStorage.setItem('refreshToken',d.refreshToken);if(d.user)localStorage.setItem('user',JSON.stringify(d.user))}
function Shell(p:{title:string;sub:string;children:React.ReactNode}){return <main className="auth"><section className="box"><div className="brand"><Building2/></div><h1>{p.title}</h1><p className="muted">{p.sub}</p>{p.children}</section></main>}
function Pwd({v,set,ph='Masukkan password'}:{v:string;set:(x:string)=>void;ph?:string}){const[s,ss]=useState(false);return <div className="input"><Lock size={18}/><input type={s?'text':'password'} value={v} onChange={e=>set(e.target.value)} placeholder={ph}/><button type="button" className="mini" onClick={()=>ss(!s)}>{s?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>}
function Home({go}:{go:(p:Page)=>void}){return <main className="page"><nav><b><Building2/> SILABU DIGI</b><span><button className="ghost" onClick={()=>go('login')}>Masuk</button><button onClick={()=>go('register')}>Daftar</button></span></nav><section className="hero"><div className="badge"><ShieldCheck size={16}/> Auth baru aktif</div><h1>Sistem Laporan BUM Desa Digital</h1><p>Project baru terstruktur. Auth pakai OTP, magic link, reset password, refresh token rotation, audit log.</p><button onClick={()=>go('register')}>Daftar BUM Desa</button><button className="ghost" onClick={()=>go('login')}>Masuk Dashboard</button></section></main>}
function Register({go}:{go:(p:Page)=>void}){const[e,se]=useState(''),[n,sn]=useState(''),[p,sp]=useState(''),[c,sc]=useState(''),[err,serr]=useState(''),[l,sl]=useState(false);async function sub(x:any){x.preventDefault();serr('');if(p!==c)return serr('Konfirmasi password tidak sama');try{sl(true);await api('/auth/register',{email:e,password:p,namaLengkap:n});localStorage.setItem('pendingEmail',e);go('verify')}catch(a:any){serr(a.message)}finally{sl(false)}}return <Shell title="Daftar Akun Baru" sub="Verifikasi email dulu, baru isi Data BUM Desa."><form onSubmit={sub} className="form"><div className="input"><Mail size={18}/><input type="email" value={e} onChange={x=>se(x.target.value)} placeholder="Masukkan email aktif" required/></div><div className="input"><Building2 size={18}/><input value={n} onChange={x=>sn(x.target.value)} placeholder="Masukkan nama lengkap" required/></div><Pwd v={p} set={sp}/><Pwd v={c} set={sc} ph="Ulangi password"/>{err&&<p className="err">{err}</p>}<button disabled={l}>{l?'Mengirim OTP...':'Daftar & Kirim OTP'}</button></form><p className="switch">Sudah punya akun? <a onClick={()=>go('login')}>Masuk</a></p></Shell>}
function Verify({go}:{go:(p:Page)=>void}){const q=new URLSearchParams(location.search),token=q.get('token'),[e,se]=useState(q.get('email')||localStorage.getItem('pendingEmail')||''),[o,so]=useState(''),[err,serr]=useState(''),[ok,sok]=useState('');async function sub(x?:any){x?.preventDefault();serr('');try{const d=await api('/auth/verify-email',token?{token,email:e}:{email:e,otp:o});save(d);sok('Email berhasil diverifikasi');setTimeout(()=>go('dashboard'),700)}catch(a:any){serr(a.message)}}return <Shell title="Verifikasi Email" sub="Masukkan OTP 6 digit atau pakai magic link."><form onSubmit={sub} className="form"><div className="input"><Mail size={18}/><input value={e} onChange={x=>se(x.target.value)} placeholder="Masukkan email"/></div>{!token&&<div className="input"><KeyRound size={18}/><input value={o} onChange={x=>so(x.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Masukkan OTP"/></div>}{err&&<p className="err">{err}</p>}{ok&&<p className="ok">{ok}</p>}<button>{token?'Verifikasi Magic Link':'Verifikasi Email'}</button></form></Shell>}
function Login({go}:{go:(p:Page)=>void}){const[e,se]=useState(''),[p,sp]=useState(''),[err,serr]=useState('');async function sub(x:any){x.preventDefault();try{const d=await api('/auth/login',{email:e,password:p});save(d);go('dashboard')}catch(a:any){if(String(a.message).includes('belum diverifikasi')){localStorage.setItem('pendingEmail',e);go('verify')}else serr(a.message)}}return <Shell title="Masuk SILABU DIGI" sub="Login dengan email terverifikasi."><form onSubmit={sub} className="form"><div className="input"><Mail size={18}/><input type="email" value={e} onChange={x=>se(x.target.value)} placeholder="Masukkan email" required/></div><Pwd v={p} set={sp}/>{err&&<p className="err">{err}</p>}<button>Masuk</button></form><p className="switch"><a onClick={()=>go('forgot')}>Lupa password?</a></p><p className="switch">Belum punya akun? <a onClick={()=>go('register')}>Daftar</a></p></Shell>}
function Forgot({go}:{go:(p:Page)=>void}){const[e,se]=useState(''),[m,sm]=useState('');async function sub(x:any){x.preventDefault();await api('/auth/forgot-password',{email:e});localStorage.setItem('resetEmail',e);sm('Jika email terdaftar, OTP/link reset dikirim.')}return <Shell title="Lupa Password" sub="Kirim OTP/link reset."><form onSubmit={sub} className="form"><div className="input"><Mail size={18}/><input type="email" value={e} onChange={x=>se(x.target.value)} placeholder="Masukkan email"/></div>{m&&<p className="ok">{m}</p>}<button>Kirim Link Reset</button></form><p className="switch"><a onClick={()=>go('reset')}>Sudah punya OTP?</a></p></Shell>}
function Reset({go}:{go:(p:Page)=>void}){const q=new URLSearchParams(location.search),token=q.get('token'),[e,se]=useState(q.get('email')||localStorage.getItem('resetEmail')||''),[o,so]=useState(''),[p,sp]=useState(''),[err,serr]=useState('');async function sub(x:any){x.preventDefault();try{await api('/auth/reset-password',token?{token,email:e,password:p}:{email:e,otp:o,password:p});go('login')}catch(a:any){serr(a.message)}}return <Shell title="Reset Password" sub="Masukkan OTP atau magic link."><form onSubmit={sub} className="form"><div className="input"><Mail size={18}/><input value={e} onChange={x=>se(x.target.value)} placeholder="Masukkan email"/></div>{!token&&<div className="input"><KeyRound size={18}/><input value={o} onChange={x=>so(x.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Masukkan OTP"/></div>}<Pwd v={p} set={sp} ph="Password baru"/>{err&&<p className="err">{err}</p>}<button>Ubah Password</button></form></Shell>}
function Dash({go}:{go:(p:Page)=>void}){const u=JSON.parse(localStorage.getItem('user')||'{}');return <main className="page"><nav><b><Building2/> SILABU DIGI</b><button onClick={()=>{localStorage.clear();go('login')}}>Keluar</button></nav><section className="hero"><div className="badge"><CheckCircle2 size={16}/> Auth aktif</div><h1>Dashboard Awal</h1><p>{u.email||'-'} · {u.role||'-'}</p><p className="ok">Berikutnya: Tenant / Profil BUM Desa.</p></section></main>}
function start():Page{let p=location.pathname;if(p.includes('login'))return'login';if(p.includes('register'))return'register';if(p.includes('verify'))return'verify';if(p.includes('forgot'))return'forgot';if(p.includes('reset'))return'reset';if(p.includes('dashboard'))return'dashboard';return'home'}
function App(){const[p,sp]=useState<Page>(start());const go=(x:Page)=>{sp(x);history.pushState({},'',x==='home'?'/':'/'+(x==='verify'?'verify-email':x==='forgot'?'forgot-password':x==='reset'?'reset-password':x))};return p==='login'?<Login go={go}/>:p==='register'?<Register go={go}/>:p==='verify'?<Verify go={go}/>:p==='forgot'?<Forgot go={go}/>:p==='reset'?<Reset go={go}/>:p==='dashboard'?<Dash go={go}/>:<Home go={go}/>}
createRoot(document.getElementById('root')!).render(<App/>);
