import { pool } from './db.js';

/**
 * BUM Desa Chart of Accounts — Kepmendesa 136/2022.
 * 302 akun.
 * Each tuple: [kode, nama, jenisAkun, kelompok, saldoNormal, isPostable, level]
 */
type CoaRow = [string, string, string, string, 'D' | 'K', boolean, number];

const DEFAULT_COA: CoaRow[] = [
  ['1.0.00.00', 'ASET', 'aset', 'aset_lain', 'D', false, 1],
  ['1.1.00.00', 'Aset Lancar', 'aset', 'aset_lancar', 'D', false, 2],
  ['1.1.01.00', 'Kas', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.01.01', 'Kas Tunai', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.01.02', 'Kas di Bank BSI', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.01.03', 'Kas di Bank Mandiri', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.01.04', 'Kas di Bank BRI', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.01.05', 'Kas di Bank BPD', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.01.98', 'Kas Kecil (Petty Cash)', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.02.00', 'Setara Kas', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.02.01', 'Deposito <= 3 bulan', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.02.99', 'Setara Kas Lainnya', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.03.00', 'Piutang', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.03.01', 'Piutang Usaha', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.03.02', 'Piutang kepada Pegawai', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.03.99', 'Piutang Lainnya', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.04.00', 'Penyisihan Piutang', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.04.01', 'Penyisihan Piutang Usaha Tak Tertagih', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.04.02', 'Penyisihan Piutang kepada Pegawai Tak Tertagih', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.04.99', 'Penyisihan Piutang Lainnya Tak Tertagih', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.05.00', 'Persediaan', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.05.01', 'Persediaan Barang Dagangan', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.05.02', 'Persediaan Bahan Baku', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.05.03', 'Persediaan Barang Dalam Proses', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.05.04', 'Persediaan Barang Jadi', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.06.00', 'Perlengkapan', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.06.01', 'Alat Tulis Kantor (ATK)', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.07.00', 'Pembayaran Dimuka', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.07.01', 'Sewa Dibayar Dimuka', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.07.02', 'Asuransi Dibayar Dimuka', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.07.03', 'PPh 25', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.07.04', 'PPN Masukan', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.98.00', 'Aset Lancar Lainnya', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.98.99', 'Aset Lancar Lainnya', 'aset', 'aset_lancar', 'D', true, 4],
  ['1.1.99.00', 'RK Unit Usaha', 'aset', 'aset_lancar', 'D', false, 3],
  ['1.1.99.01', 'RK Unit Wisata', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.02', 'RK Unit Restoran', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.03', 'RK Unit Minimart Desa', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.04', 'RK Unit Gedung Serbaguna', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.05', 'RK Unit Simpan Pinjam', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.06', 'RK Unit Pengelolaan Air Bersih', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.1.99.07', 'RK Unit Pengelolaan Sampah', 'aset', 'aset_lancar', 'K', true, 4],
  ['1.2.00.00', 'Investasi', 'aset', 'investasi', 'D', false, 2],
  ['1.2.01.00', 'Investasi', 'aset', 'investasi', 'D', false, 3],
  ['1.2.01.01', 'Deposito > 3 bulan', 'aset', 'investasi', 'D', true, 4],
  ['1.2.01.99', 'Investasi Lainnya', 'aset', 'investasi', 'D', true, 4],
  ['1.3.00.00', 'Aset Tetap', 'aset', 'aset_tetap', 'D', false, 2],
  ['1.3.01.00', 'Tanah', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.01.01', 'Tanah', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.02.00', 'Kendaraan', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.02.01', 'Kendaraan', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.03.00', 'Peralatan dan Mesin', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.03.01', 'Peralatan dan Mesin', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.04.00', 'Meubelair', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.04.01', 'Meubelair', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.05.00', 'Gedung dan Bangunan', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.05.01', 'Gedung dan Bangunan', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.06.00', 'Konstruksi Dalam Pengerjaan', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.06.01', 'Konstruksi Dalam Pengerjaan', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.3.07.00', 'Akumulasi Penyusutan Aset Tetap', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.07.01', 'Akumulasi Penyusutan Kendaraan', 'aset', 'aset_tetap', 'K', true, 4],
  ['1.3.07.02', 'Akumulasi Penyusutan Peralatan dan Mesin', 'aset', 'aset_tetap', 'K', true, 4],
  ['1.3.07.03', 'Akumulasi Penyusutan Meubelair', 'aset', 'aset_tetap', 'K', true, 4],
  ['1.3.07.04', 'Akumulasi Penyusutan Gedung dan Bangunan', 'aset', 'aset_tetap', 'K', true, 4],
  ['1.3.99.00', 'Aset Tetap Lainnya', 'aset', 'aset_tetap', 'D', false, 3],
  ['1.3.99.99', 'Aset Tetap Lainnya', 'aset', 'aset_tetap', 'D', true, 4],
  ['1.4.00.00', 'Aset takberwujud', 'aset', 'aset_tak_berwujud', 'D', false, 2],
  ['1.4.01.00', 'Aset takberwujud', 'aset', 'aset_tak_berwujud', 'D', false, 3],
  ['1.4.01.01', 'Software', 'aset', 'aset_tak_berwujud', 'D', true, 4],
  ['1.4.01.02', 'Patent', 'aset', 'aset_tak_berwujud', 'D', true, 4],
  ['1.4.01.03', 'Trademark', 'aset', 'aset_tak_berwujud', 'D', true, 4],
  ['1.4.02.00', 'Amortisasi Aset takberwujud', 'aset', 'aset_tak_berwujud', 'D', false, 3],
  ['1.4.02.01', 'Amortisasi Aset takberwujud', 'aset', 'aset_tak_berwujud', 'D', true, 4],
  ['1.9.00.00', 'Aset Lain-lain', 'aset', 'aset_lain', 'D', false, 2],
  ['1.9.01.00', 'Aset Lain-lain', 'aset', 'aset_lain', 'D', false, 3],
  ['1.9.01.01', 'Aset Lain-lain', 'aset', 'aset_lain', 'D', true, 4],
  ['1.9.02.00', 'Akumulasi Penyusutan Aset Lain-lain', 'aset', 'aset_lain', 'D', false, 3],
  ['1.9.02.01', 'Akumulasi Penyusutan Aset Lain-lain', 'aset', 'aset_lain', 'D', true, 4],
  ['2.0.00.00', 'KEWAJIBAN', 'kewajiban', 'kewajiban_jk_panjang', 'K', false, 1],
  ['2.1.00.00', 'Kewajiban Jangka Pendek', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 2],
  ['2.1.01.00', 'Utang Usaha', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.01.01', 'Utang Usaha', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.02.00', 'Utang Pajak', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.02.01', 'PPN Keluaran', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.02.02', 'PPh 21', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.02.03', 'PPh 23', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.02.04', 'PPh 29', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.03.00', 'Utang Gaji/Upah dan Tunjangan', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.03.01', 'Utang Gaji dan Tunjangan', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.03.02', 'Utang Gaji/Upah Karyawan', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.04.00', 'Utang Utilitas', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.04.01', 'Utang Listrik', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.04.02', 'Utang Telepon/Internet', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.04.93', 'Utang Utilitas Lainnya', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.05.00', 'Utang kepada Pihak Ketiga Jk. Pendek', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.05.01', 'Utang kepada Pihak Ketiga Jk. Pendek', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.05.99', 'Utang kepada Pihak Ketiga Jk. Pendek Lainnya', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.1.99.00', 'Utang Jangka Pendek Lainnya', 'kewajiban', 'kewajiban_jk_pendek', 'K', false, 3],
  ['2.1.99.99', 'Utang Jangka Pendek Lainnya', 'kewajiban', 'kewajiban_jk_pendek', 'K', true, 4],
  ['2.2.00.00', 'Kewajiban Jangka Panjang', 'kewajiban', 'kewajiban_jk_panjang', 'K', false, 2],
  ['2.2.01.00', 'Utang Ke Bank', 'kewajiban', 'kewajiban_jk_panjang', 'K', false, 3],
  ['2.2.01.01', 'Utang Ke Bank', 'kewajiban', 'kewajiban_jk_panjang', 'K', true, 4],
  ['2.2.02.00', 'Utang kepada Pihak Ketiga Jk. Panjang', 'kewajiban', 'kewajiban_jk_panjang', 'K', false, 3],
  ['2.2.02.01', 'Utang kepada Pihak Ketiga Jk. Panjang', 'kewajiban', 'kewajiban_jk_panjang', 'K', true, 4],
  ['2.2.99.00', 'Utang Jangka Panjang Lainnya', 'kewajiban', 'kewajiban_jk_panjang', 'K', false, 3],
  ['2.2.99.99', 'Utang Jangka Panjang Lainnya', 'kewajiban', 'kewajiban_jk_panjang', 'K', true, 4],
  ['3.0.00.00', 'EKUITAS', 'ekuitas', 'ekuitas', 'K', false, 1],
  ['3.1.00.00', 'Modal Pemilik', 'ekuitas', 'modal_pemilik', 'K', false, 2],
  ['3.1.01.00', 'Penyertaan Modal Desa', 'ekuitas', 'modal_pemilik', 'K', false, 3],
  ['3.1.01.01', 'Penyertaan Modal Desa', 'ekuitas', 'modal_pemilik', 'K', true, 4],
  ['3.1.02.00', 'Penyertaan Modal Masyarakat', 'ekuitas', 'modal_pemilik', 'K', false, 3],
  ['3.1.02.01', 'Penyertaan Modal Masyarakat A', 'ekuitas', 'modal_pemilik', 'K', true, 4],
  ['3.1.02.02', 'Penyertaan Modal Masyarakat B', 'ekuitas', 'modal_pemilik', 'K', true, 4],
  ['3.1.02.03', 'Penyertaan Modal Masyarakat C', 'ekuitas', 'modal_pemilik', 'K', true, 4],
  ['3.1.02.04', 'Penyertaan Modal Masyarakat D', 'ekuitas', 'modal_pemilik', 'K', true, 4],
  ['3.2.00.00', 'Pengambilan oleh Pemilik', 'ekuitas', 'pengambilan_pemilik', 'K', false, 2],
  ['3.2.01.00', 'Bagi Hasil Penyertaan Modal Desa', 'ekuitas', 'pengambilan_pemilik', 'K', false, 3],
  ['3.2.01.01', 'Bagi Hasil Penyertaan Modal Desa', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.01.02', 'Bagi Hasil Penyertaan Modal Desa A', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.01.03', 'Bagi Hasil Penyertaan Modal Desa B', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.01.04', 'Bagi Hasil Penyertaan Modal Desa C', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.02.00', 'Bagi Hasil Penyertaan Modal Masyarakat', 'ekuitas', 'pengambilan_pemilik', 'K', false, 3],
  ['3.2.02.01', 'Bagi Hasil Penyertaan Modal Masyarakat', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.02.02', 'Bagi Hasil Penyertaan Modal Masyarakat Desa A', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.02.03', 'Bagi Hasil Penyertaan Modal Masyarakat Desa B', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.2.02.04', 'Bagi Hasil Penyertaan Modal Masyarakat Desa C', 'ekuitas', 'pengambilan_pemilik', 'D', true, 4],
  ['3.3.00.00', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'K', false, 2],
  ['3.3.01.00', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'K', false, 3],
  ['3.3.01.01', 'Saldo Laba Tidak Dicadangkan', 'ekuitas', 'saldo_laba', 'K', true, 4],
  ['3.3.01.02', 'Saldo Laba Dicadangkan untuk Pembelian Aset Tetap', 'ekuitas', 'saldo_laba', 'K', true, 4],
  ['3.3.01.03', 'Saldo Laba Dicadangkan untuk Pembayaran Utang Jangka Panjang', 'ekuitas', 'saldo_laba', 'K', true, 4],
  ['3.4.00.00', 'Modal Donasi/Sumbangan', 'ekuitas', 'modal_donasi', 'K', false, 2],
  ['3.4.01.00', 'Modal Donasi/Sumbangan', 'ekuitas', 'modal_donasi', 'K', false, 3],
  ['3.4.01.01', 'Modal Donasi/Sumbangan', 'ekuitas', 'modal_donasi', 'K', true, 4],
  ['3.8.00.00', 'RK Pusat', 'ekuitas', 'rk_pusat', 'K', false, 2],
  ['3.8.01.00', 'RK Pusat', 'ekuitas', 'rk_pusat', 'K', false, 3],
  ['3.8.01.01', 'RK Pusat', 'ekuitas', 'rk_pusat', 'D', true, 4],
  ['3.9.00.00', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'K', false, 2],
  ['3.9.01.00', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'K', false, 3],
  ['3.9.01.01', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'K', true, 4],
  ['4.0.00.00', 'PENDAPATAN USAHA', 'pendapatan', 'pendapatan', 'K', false, 1],
  ['4.1.00.00', 'Pendapatan Jasa', 'pendapatan', 'pendapatan_jasa', 'K', false, 2],
  ['4.1.01.00', 'Pendapatan Wisata', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.01.01', 'Pendapatan Tiket', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.01.02', 'Pendapatan Wahana', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.01.03', 'Pendapatan Paket Wisata', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.02.00', 'Pendapatan Pengelolaan Air Bersih', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.02.01', 'Pendapatan Pengelolaan Air Bersih', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.03.00', 'Pendapatan Pengelolaan Sampah', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.03.01', 'Pendapatan Pengelolaan Sampah', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.00', 'Pendapatan Sewa', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.04.01', 'Pendapatan Sewa Tempat Outbound', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.02', 'Pendapatan Sewa Tempat untuk Toko/Kios', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.03', 'Pendapatan Sewa Gedung', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.04', 'Pendapatan Sewa Mobil', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.05', 'Pendapatan Sewa Peralatan Gedung', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.04.99', 'Pendapatan Sewa Lainnya', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.05.00', 'Pendapatan Jasa Pelayanan', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.05.01', 'Pendapatan Jasa Pembayaran Listrik', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.05.99', 'Pendapatan Jasa Pelayanan lainnya', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.06.00', 'Pendapatan Transportasi', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.06.01', 'Pendapatan Transportasi', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.07.00', 'Pendapatan Parkir', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.07.01', 'Pendapatan Parkir Mobil', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.07.02', 'Pendapatan Parkir Motor', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.08.00', 'Pendapatan Simpan Pinjam', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.08.01', 'Pendapatan Simpan Pinjam', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.09.00', 'Pendapatan Pelatihan', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.09.01', 'Pendapatan Pelatihan', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.10.00', 'Pendapatan Penginapan/Homestay', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.10.01', 'Pendapatan Homestay', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.1.11.00', 'Pendapatan Komisi', 'pendapatan', 'pendapatan_jasa', 'K', false, 3],
  ['4.1.11.01', 'Pendapata Komisi', 'pendapatan', 'pendapatan_jasa', 'K', true, 4],
  ['4.2.00.00', 'Pendapatan Penjualan Barang Dagangan', 'pendapatan', 'penjualan_barang_dagangan', 'K', false, 2],
  ['4.2.01.00', 'Pendapatan Penjualan Barang Dagangan', 'pendapatan', 'penjualan_barang_dagangan', 'K', false, 3],
  ['4.2.01.01', 'Pendapatan Penjualan Makanan/Minuman', 'pendapatan', 'penjualan_barang_dagangan', 'K', true, 4],
  ['4.2.01.04', '4.2.01.03 Kerajinan/Suvenir 4 Pendapatan Penjualan Buku', 'pendapatan', 'penjualan_barang_dagangan', 'K', true, 4],
  ['4.2.01.05', 'Pendapatan Penjualan Biji Kopi', 'pendapatan', 'penjualan_barang_dagangan', 'K', true, 4],
  ['4.2.01.06', 'Pendapatan Penjualan Bensin', 'pendapatan', 'penjualan_barang_dagangan', 'K', true, 4],
  ['4.2.01.99', 'Diskon Penjualan Barang Dagangan', 'pendapatan', 'penjualan_barang_dagangan', 'K', true, 4],
  ['4.3.00.00', 'Pendapatan Penjualan Barang Jadi', 'pendapatan', 'penjualan_barang_jadi', 'K', false, 2],
  ['4.3.01.00', 'Pendapatan Penjualan Barang Jadi', 'pendapatan', 'penjualan_barang_jadi', 'K', false, 3],
  ['4.3.01.01', 'Pendapatan Katering', 'pendapatan', 'penjualan_barang_jadi', 'K', true, 4],
  ['4.3.01.02', 'Pendapatan Restoran', 'pendapatan', 'penjualan_barang_jadi', 'K', true, 4],
  ['4.3.01.03', 'Pendapatan Kopi', 'pendapatan', 'penjualan_barang_jadi', 'K', true, 4],
  ['4.3.01.04', 'Diskon Penjualan Barang Jadi', 'pendapatan', 'penjualan_barang_jadi', 'K', true, 4],
  ['5.0.00.00', 'HARGA POKOK PRODUKSI DAN PENJUALAN', 'hpp', 'hpp', 'D', false, 1],
  ['5.1.00.00', 'Harga Pokok Penjualan Barang Dagangan', 'hpp', 'hpp_barang_dagangan', 'D', false, 2],
  ['5.1.01.00', 'Harga Pokok Penjualan Barang Dagangan', 'hpp', 'hpp_barang_dagangan', 'D', false, 3],
  ['5.1.01.01', 'Harga Pokok Penjualan Barang Dagangan', 'hpp', 'hpp_barang_dagangan', 'D', true, 4],
  ['5.2.00.00', 'Harga Pokok Penjualan Barang Jadi', 'hpp', 'hpp_barang_jadi', 'D', false, 2],
  ['5.2.01.00', 'Harga Pokok Penjualan Barang Jadi', 'hpp', 'hpp_barang_jadi', 'D', false, 3],
  ['5.2.01.01', 'Harga Pokok Penjualan Barang Jadi', 'hpp', 'hpp_barang_jadi', 'D', true, 4],
  ['5.3.00.00', 'Harga Pokok Produksi', 'hpp', 'hpp_produksi', 'D', false, 2],
  ['5.3.01.00', 'Harga Pokok Produksi', 'hpp', 'hpp_produksi', 'D', false, 3],
  ['5.3.01.01', 'Harga Pokok Produksi', 'hpp', 'hpp_produksi', 'D', true, 4],
  ['6.0.00.00', 'BEBAN-BEBAN USAHA', 'beban', 'beban', 'D', false, 1],
  ['6.1.00.00', 'Beban Administrasi dan Umum', 'beban', 'beban_adum', 'D', false, 2],
  ['6.1.01.00', 'Beban Pegawai Bagian Administrasi Umum', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.01.01', 'Beban Gaji dan Tunjangan Bag. Adum', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.02', 'Beban Honor Lembur Bag. Adum', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.03', 'Beban Honor Narasumber', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.04', 'Beban Insentif (Bonus) Bag. Adum', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.05', 'Beban Komisi Bag. Adum', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.06', 'Beban Seragam Pegawai Bag. Adum', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.07', 'Beban Penguatan SDM', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.01.99', 'Beban Pegawai Bag. Adum Lainnya', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.02.00', 'Beban Perlengkapan', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.02.01', 'Beban Alat Tulis Kantor (ATK)', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.02.02', 'Beban Foto Copy', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.02.03', 'Beban Konsumsi Rapat', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.02.04', 'Beban Cetak dan Dekorasi', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.02.99', 'Beban Perlengkapan Lainnya', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.03.00', 'Beban Pemeliharaan dan Perbaikan', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.03.01', 'Beban Pemeliharaan dan Perbaikan', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.04.00', 'Beban Utilitas', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.04.01', 'Beban Listrik', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.04.02', 'Beban Telepon/Internet', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.04.99', 'Beban Utilitas Lainnya', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.05.00', 'Beban Sewa dan Asuransi', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.05.01', 'Beban Sewa', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.05.02', 'Beban Asuransi', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.06.00', 'Beban Kebersihan dan Keamanan', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.06.01', 'Beban Kebersihan', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.06.02', 'Beban Keamanan', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.00', 'Beban Penyisihan dan Penyusutan/Amortisasi', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.07.01', 'Beban Penyisihan Piutang Tak Tertagih', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.02', 'Beban Penyusutan Kendaraan', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.03', 'Beban Penyusutan Peralatan dan Mesin', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.04', 'Beban Penyusutan Meubelair', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.05', 'Beban Penyusutan Gedung dan Bangunan', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.07.06', 'Beban Amortisasi Aset takberwujud', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.00', 'Beban Administrasi dan Umum Lainnya', 'beban', 'beban_adum', 'D', false, 3],
  ['6.1.99.01', 'Beban Parkir', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.02', 'Beban Audit', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.03', 'Beban Perjalanan Dinas', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.04', 'Beban Transportasi', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.05', 'Beban Jamuan Tamu', 'beban', 'beban_adum', 'D', true, 4],
  ['6.1.99.99', 'Beban Administrasi dan Umum Lainnya', 'beban', 'beban_adum', 'D', true, 4],
  ['6.2.00.00', 'Beban Operasional', 'beban', 'beban_operasional', 'D', false, 2],
  ['6.2.01.00', 'Beban Pegawai Bagian Operasional', 'beban', 'beban_operasional', 'D', false, 3],
  ['6.2.01.01', 'Beban Gaji/Upah Bag. Operasional', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.01.02', 'Beban Uang Makan Bag. Operasional', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.02.00', 'Beban Pemeliharaan dan Perbaikan', 'beban', 'beban_operasional', 'D', false, 3],
  ['6.2.02.01', 'Beban Pemeliharaan Wahana', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.02.02', 'Beban Perbaikan dan Renovasi', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.03.00', 'Beban Keamanan', 'beban', 'beban_operasional', 'D', false, 3],
  ['6.2.03.01', 'Beban Tim SAR', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.03.02', 'Beban P3K', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.99.00', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'D', false, 3],
  ['6.2.99.01', 'Beban Komunikasi', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.99.02', 'Beban Sewa Lokasi', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.99.03', 'Beban Pakan Ikan', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.2.99.99', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'D', true, 4],
  ['6.3.00.00', 'Beban Pemasaran', 'beban', 'beban_pemasaran', 'D', false, 2],
  ['6.3.01.00', 'Beban Pegawai Bagian Pemasaran', 'beban', 'beban_pemasaran', 'D', false, 3],
  ['6.3.01.01', 'Beban Gaji/Upah Bag. Pemasaran', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.01.02', 'Beban Insentif (Bonus) Bag. Pemasaran', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.01.03', 'Beban Seragam Pegawai Bag. Pemasaran', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.02.00', 'Beban Iklan dan Promosi', 'beban', 'beban_pemasaran', 'D', false, 3],
  ['6.3.02.01', 'Beban Iklan', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.02.02', 'Beban Promosi wartawan', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.02.03', 'Beban Dana Sosial', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['6.3.99.00', 'Beban Pemasaran Lainnya', 'beban', 'beban_pemasaran', 'D', false, 3],
  ['6.3.99.99', 'Beban Pemasaran Lainnya', 'beban', 'beban_pemasaran', 'D', true, 4],
  ['7.0.00.00', 'PENDAPATAN DAN BEBAN LAIN-LAIN', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 1],
  ['7.1.00.00', 'Pendapatan Lain-lain', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 2],
  ['7.1.01.00', 'Pendapatan dari Bank', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.01.01', 'Pendapatan Bunga Bank', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.01.02', 'Pendapatan Fee Agen BNI 46', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.02.00', 'Pendapatan Dividen', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.02.01', 'Pendapatan Dividen', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.03.00', 'Pendapatan Denda', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.03.01', 'Pendapatan Denda', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.04.00', 'Pendapatan Iklan', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.04.01', 'Pendapatan Iklan', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.05.00', 'Pendapatan Penjualan Aset Tetap', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.05.01', 'Keuntungan Penjualan Aset Tetap', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.1.99.00', 'Pendapatan Lain-lain lainnya', 'pendapatan_lain', 'pendapatan_lain', 'K', false, 3],
  ['7.1.99.99', 'Pendapatan Lain-lain lainnya', 'pendapatan_lain', 'pendapatan_lain', 'K', true, 4],
  ['7.2.00.00', 'Beban Lain-lain', 'beban_lain', 'beban_lain', 'D', false, 2],
  ['7.2.01.00', 'Beban Bank', 'beban_lain', 'beban_lain', 'D', false, 3],
  ['7.2.01.01', 'Beban Administrasi Bank', 'beban_lain', 'beban_lain', 'D', true, 4],
  ['7.2.02.00', 'Beban Bunga', 'beban_lain', 'beban_lain', 'D', false, 3],
  ['7.2.02.01', 'Beban Bunga', 'beban_lain', 'beban_lain', 'D', true, 4],
  ['7.2.03.00', 'Beban Denda', 'beban_lain', 'beban_lain', 'D', false, 3],
  ['7.2.03.01', 'Beban Denda', 'beban_lain', 'beban_lain', 'D', true, 4],
  ['7.2.04.00', 'Beban Penjualan Aset Tetap', 'beban_lain', 'beban_lain', 'D', false, 3],
  ['7.2.04.01', 'Kerugian Penjualan Aset Tetap', 'beban_lain', 'beban_lain', 'D', true, 4],
  ['7.2.99.00', 'Beban Lain-lain Lainnya', 'beban_lain', 'beban_lain', 'D', false, 3],
  ['7.2.99.99', 'Beban Lain-lain lainnya', 'beban_lain', 'beban_lain', 'D', true, 4],
  ['7.3.00.00', 'Beban Pajak', 'beban_pajak', 'pajak', 'D', false, 2],
  ['7.3.01.00', 'Beban Pajak', 'beban_pajak', 'pajak', 'D', false, 3],
  ['7.3.01.01', 'Beban Pajak Air Permukaan', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.02', 'Beban Pajak Bunga Bank', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.03', 'Beban Pajak Daerah', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.04', 'Beban Pajak Hiburan', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.05', 'Beban Pajak Reklame', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.06', 'Beban PPh 21', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.07', 'Beban PPh 23', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.08', 'Beban PPh 25', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.09', 'Beban PPh 29', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.10', 'Beban PPh Final', 'beban_pajak', 'pajak', 'D', true, 4],
  ['7.3.01.99', 'Beban Pajak Lainnya', 'beban_pajak', 'pajak', 'D', true, 4],
];

function parentKode(kode: string, level: number): string | null {
  if (level <= 1) return null;
  const parts = kode.split('.');
  const idx = level - 1;
  const zeroed = parts.map((p, i) => {
    if (i < idx) return p;
    return i === 0 ? '0' : '00';
  });
  return zeroed.join('.');
}

export async function seedDefaultCoa(tenantId: string): Promise<void> {
  const existing = await pool.query(
    'SELECT 1 FROM chart_of_accounts WHERE tenant_id=$1 LIMIT 1',
    [tenantId]
  );
  if (existing.rowCount) return;

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const idByKode = new Map<string, string>();

    for (const [kode, nama, jenisAkun, kelompok, saldoNormal, isPostable, level] of DEFAULT_COA) {
      const pk = parentKode(kode, level);
      const parentId = pk ? idByKode.get(pk) ?? null : null;
      const res = await client.query(
        `INSERT INTO chart_of_accounts
           (tenant_id, kode, nama, jenisAkun, kelompok, saldoNormal, isPostable, parent_id, is_seeded, is_system_default, isActive, level)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,true,true,true,$9)
         RETURNING id`,
        [tenantId, kode, nama, jenisAkun, kelompok, saldoNormal, isPostable, parentId, level]
      );
      idByKode.set(kode, res.rows[0].id as string);
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}
