import React,{useState}from'react';import{Building2,Mail,Lock,Eye,EyeOff,ArrowLeft,LogOut,Menu,X}from'lucide-react';
export type Page='home'|'login'|'register'|'verify'|'forgot'|'reset'|'dashboard';
export const API='/api';
export async function api(path:string,body:any){const r=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request gagal');return d}
export function saveAuth(d:any){if(d.accessToken)localStorage.setItem('accessToken',d.accessToken);if(d.refreshToken)localStorage.setItem('refreshToken',d.refreshToken);if(d.user)localStorage.setItem('user',JSON.stringify(d.user))}
export function BackBtn({go,target}:{go:(p:Page)=>void;target?:Page}){return <button className="back-btn" onClick={()=>go(target||'home')}><ArrowLeft size={20}/> Kembali</button>}
export function AuthShell({title,subtitle,backTarget,go,children}:{title:string;subtitle:string;backTarget?:Page;go:(p:Page)=>void;children:React.ReactNode}){return <main className="auth-page"><div className="auth-container"><BackBtn go={go} target={backTarget}/><section className="auth-card anim-card"><img src="/logo.png" alt="SILABU DIGI" className="brand-logo"/><h1>{title}</h1><p className="auth-sub">{subtitle}</p>{children}</section></div></main>}
export function PasswordInput({value,onChange,placeholder='Masukkan password'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){const[show,setShow]=useState(false);return <div className="field"><Lock size={18} className="field-icon"/><input type={show?'text':'password'} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><button type="button" className="toggle-btn" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>}
export function Navbar({go,loggedIn}:{go:(p:Page)=>void;loggedIn?:boolean}){const[open,setOpen]=useState(false);return <nav className="nav"><div className="nav-inner"><div className="nav-brand" onClick={()=>go('home')}><img src="/logo.png" alt="SILABU DIGI" className="nav-logo"/></div><div className={`nav-links ${open?'open':''}`}>{loggedIn?<button className="btn-outline" onClick={()=>{localStorage.clear();go('login')}}><LogOut size={16}/> Keluar</button>:<><button className="btn-outline" onClick={()=>{setOpen(false);go('login')}}>Masuk</button><button className="btn-primary" onClick={()=>{setOpen(false);go('register')}}>Daftar Gratis</button></>}</div><button className="hamburger" onClick={()=>setOpen(!open)}>{open?<X size={24}/>:<Menu size={24}/>}</button></div></nav>}
export const MailField=({value,set,placeholder='Masukkan email'}:{value:string;set:(v:string)=>void;placeholder?:string})=><div className="field"><Mail size={18} className="field-icon"/><input type="email" value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} required/></div>;
export const NameField=({value,set}:{value:string;set:(v:string)=>void})=><div className="field"><Building2 size={18} className="field-icon"/><input value={value} onChange={e=>set(e.target.value)} placeholder="Masukkan nama lengkap" required/></div>;
